baseURL: "https://softoise.com/"
theme: "up-business-theme"
languageCode: "es-mx" 

title: "Softoise"

# googleAnalytics: ""

summaryLength: 20 # The length of the summary of the post

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  title: "Softoise"
  description: "We specialize in providing services to desing websites, applications, build and maintain business for customers."
  images: 
    - "images/hero-image.png"

  logo: "landing/images/logo-black.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  ogTags:
    type: "company"
    image: "images/perfil.jpg"
    description: "custom software solutions"
    # twitter:
    #   site: "@softoise"
    #   creator: "@softoise"

  social:
    # dribbble: "#"
    instagram: "https://www.instagram.com/softoise"
    # facebook: ""
    # twitter: "#"

  location:
    - "León Guanajuato, México"
    # - "4517 Washington Ave. Manchester, Kentucky 39495"

  contact:
    - "softoise@outlook.com"
    - "477 301 0668"

  copyright: "© 2025 Softoise All Rights Reserved"

menus:
  main:
    - name: "Inicio"
      url: "/"
      weight: 1

    - name: "Nosotros"
      url: "/our-work"
      weight: 2

    - name: "Pricing"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Agenda una reunión"
      url: "https://calendly.com/softoise/30min"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Pricing"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
